from binaryninja_cortex.platforms import MCU

class Chip(MCU):
    NAME="LPC43XX_M4"
    ROM_OFF=0x1A000000 
    RAM_OFF=0x10000000 

    IRQ=MCU.IRQ+ [
        "NVIC_EVENTROUTER_IRQ",
        "NVIC_C_CAN1_IRQ",
        "NVIC_WWDT_IRQ",
        "NVIC_QEI_IRQ",
        "NVIC_USART0_IRQ",
        "NVIC_UART1_IRQ",
        "NVIC_USART2_IRQ",
        "NVIC_USART3_IRQ",
        "NVIC_SPI_IRQ",
        "NVIC_ADC1_IRQ",
        "NVIC_SSP0_IRQ",
        "NVIC_SSP1_IRQ",
        "NVIC_ATIMER_IRQ",
        "NVIC_RTC_IRQ",
        "NVIC_I2S0_IRQ",
        "NVIC_I2S1_IRQ",
        "NVIC_GINT0_IRQ",
        "NVIC_GINT1_IRQ",
        "NVIC_M0CORE_IRQ",
        "NVIC_DAC_IRQ",
        "NVIC_DMA_IRQ",
        "NVIC_ETHERNET_IRQ",
        "NVIC_LCD_IRQ",
        "NVIC_SDIO_IRQ",
        "NVIC_USB1_IRQ",
        "NVIC_USB0_IRQ",
        "NVIC_C_CAN0_IRQ",
        "NVIC_PIN_INT7_IRQ",
        "NVIC_PIN_INT6_IRQ",
        "NVIC_RITIMER_IRQ",
        "NVIC_SCT_IRQ",
        "NVIC_TIMER1_IRQ",
        "NVIC_TIMER0_IRQ",
        "NVIC_TIMER3_IRQ",
        "NVIC_TIMER2_IRQ",
        "NVIC_ADC0_IRQ",
        "NVIC_MCPWM_IRQ",
        "NVIC_I2C1_IRQ",
        "NVIC_I2C0_IRQ",
        "NVIC_SGPIO_IRQ",
        "NVIC_SPIFI_IRQ",
        "NVIC_PIN_INT5_IRQ",
        "NVIC_PIN_INT4_IRQ",
        "NVIC_PIN_INT3_IRQ",
        "NVIC_PIN_INT2_IRQ",
        "NVIC_PIN_INT1_IRQ",
        "NVIC_PIN_INT0_IRQ",
        ]
